/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define GPIOB_BASE (0x48000400)
#define RCC_AHB1 ((volatile unsigned int*)(0x40021000 + 0x14))

#define GPIOB_MODER ((volatile unsigned int*)(GPIOB_BASE + 0x00))
#define GPIOB_ODR ((volatile unsigned int *)(GPIOB_BASE + 0x14))

int main(void)
{
volatile unsigned int wt;

  /* INICIALIZACIONES */

  *RCC_AHB1 |= 0x00060000;

  *GPIOB_MODER &= ~0x000000C0;	// el simbolo ~ sirve para invertir el número hexadecimal
  *GPIOB_MODER |= 0x00000040;

  /* BUCLE PRINCIPAL */

for(;;)
  {
	*GPIOB_ODR |= 0x00000008;		/* Salida nivel alto */
	wt = 1000000;			/* Espera */
	while(wt != 0)
		{
			wt--;
		}

	*GPIOB_ODR &= ~0x00000008;	/* Salida nivel bajo */
	wt = 100000;			/* Espera */
	while(wt != 0)
		{
			wt--;
		}
	  }
}

